# -------------------------------------------------------------------------------------
#
# Copyright (c) 2023, WSO2 LLC. (http://www.wso2.com). All Rights Reserved.
#
# This software is the property of WSO2 LLC. and its suppliers, if any.
# Dissemination of any information or reproduction of any material contained 
# herein is strictly forbidden, unless permitted by WSO2 in accordance with the 
# WSO2 Commercial License available at https://wso2.com/licenses/eula/3.2
#
# --------------------------------------------------------------------------------------

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "resource.prefix" . }}-{{ .Release.Name }}-carbonapps
  namespace : {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.wso2.deployment.storage.capacity }}
  storageClassName: {{ .Values.wso2.deployment.storage.storageClass }}
