{{- if and (eq "gcp" .Values.provider) (.Values.wso2.deployment.mountCapps) }}
# -------------------------------------------------------------------------------------
#
# Copyright (c) 2023, WSO2 LLC. (http://www.wso2.com). All Rights Reserved.
#
# This software is the property of WSO2 LLC. and its suppliers, if any.
# Dissemination of any information or reproduction of any material contained 
# herein is strictly forbidden, unless permitted by WSO2 in accordance with the 
# WSO2 Commercial License available at https://wso2.com/licenses/eula/3.2
#
# --------------------------------------------------------------------------------------

apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "resource.prefix" . }}-{{ .Release.Name }}-carbonapps
spec:
  capacity:
    storage: {{ .Values.gcp.storage.capacity }}
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  storageClassName: {{ .Values.gcp.storage.storageClass }}
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: filestore.csi.storage.gke.io
    volumeHandle: {{ .Values.gcp.storage.volumeHandle }}
    volumeAttributes:
      ip: {{ .Values.gcp.storage.volumeAttributes.ip }}
      volume: {{ .Values.gcp.storage.volumeAttributes.volume }}
{{- end}}
