{{- if .Values.wso2.ingress.metrics }}
# -------------------------------------------------------------------------------------
#
# Copyright (c) 2023, WSO2 LLC. (http://www.wso2.com). All Rights Reserved.
#
# This software is the property of WSO2 LLC. and its suppliers, if any.
# Dissemination of any information or reproduction of any material contained 
# herein is strictly forbidden, unless permitted by WSO2 in accordance with the 
# WSO2 Commercial License available at https://wso2.com/licenses/eula/3.2
#
# --------------------------------------------------------------------------------------

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "resource.prefix" . }}-{{ .Release.Name }}-metrics
  namespace : {{ .Release.Namespace }}
{{- if .Values.wso2.ingress.metrics.annotations }}
  annotations:
{{ toYaml .Values.wso2.ingress.metrics.annotations | indent 4 }}
{{- if .Values.wso2.ingress.ratelimit.enabled }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      limit_req zone={{ .Values.wso2.ingress.ratelimit.zoneName }} burst={{ .Values.wso2.ingress.ratelimit.burstLimit }} nodelay;                                                   
      limit_req_status 429;
{{- end }}
{{- end }}
spec:
  ingressClassName: {{ .Values.wso2.ingress.ingressClassName }}
  tls:
    - hosts:
      - {{ .Values.wso2.deployment.hostname | quote }}
      secretName: {{ .Values.wso2.ingress.tlsSecret }}
  rules:
    - host: {{ .Values.wso2.deployment.hostname | quote }}
      http:
        paths:
          - path: /healthz
            pathType: Exact
            backend:
              service:
                name: {{ template "resource.prefix" . }}-{{ .Release.Name }}
                port:
                  number: {{ add 9201 .Values.wso2.config.portOffset -10 }}
{{- end}}
