
{{- if and (eq "aws" .Values.provider) (.Values.wso2.config.secureVault.enabled) }}

# -------------------------------------------------------------------------------------
#
# Copyright (c) 2023, WSO2 LLC. (http://www.wso2.com). All Rights Reserved.
#
# This software is the property of WSO2 LLC. and its suppliers, if any.
# Dissemination of any information or reproduction of any material contained 
# herein is strictly forbidden, unless permitted by WSO2 in accordance with the 
# WSO2 Commercial License available at https://wso2.com/licenses/eula/3.2
#
# --------------------------------------------------------------------------------------

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.aws.secretManager.secretProviderClass }}
spec:
  provider: aws
  parameters:
    region: {{ .Values.aws.region }}
    objects:  |
        - objectName: {{ .Values.aws.secretManager.secretIdentifiers.internalKeystorePassword.secretName }}
          objectType: secretsmanager
          jmesPath:
            - path: {{ .Values.aws.secretManager.secretIdentifiers.internalKeystorePassword.secretKey }}
              objectAlias: {{ .Values.aws.secretManager.secretIdentifiers.internalKeystorePassword.secretKey }}
{{- end }}
