{{- if and (eq "aws" .Values.provider) (.Values.wso2.deployment.mountCapps) }}
# -------------------------------------------------------------------------------------
#
# Copyright (c) 2023, WSO2 LLC. (http://www.wso2.com). All Rights Reserved.
#
# This software is the property of WSO2 LLC. and its suppliers, if any.
# Dissemination of any information or reproduction of any material contained 
# herein is strictly forbidden, unless permitted by WSO2 in accordance with the 
# WSO2 Commercial License available at https://wso2.com/licenses/eula/3.2
#
# --------------------------------------------------------------------------------------

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Values.aws.storage.storageClass }}
provisioner: {{ .Values.aws.storage.provisioner }}
parameters:
  provisioningMode: efs-ap
  fileSystemId: {{ .Values.aws.storage.fileSystemId | quote }}
  directoryPerms: {{ .Values.aws.storage.directoryPerms | quote }}
  uid: {{ .Values.wso2.deployment.securityContext.runAsUser | quote }}
  gid: {{ .Values.wso2.deployment.securityContext.runAsUser | quote }}
{{- end}}
