
# -------------------------------------------------------------------------------------
#
# Copyright (c) 2023, WSO2 LLC. (http://www.wso2.com). All Rights Reserved.
#
# This software is the property of WSO2 LLC. and its suppliers, if any.
# Dissemination of any information or reproduction of any material contained 
# herein is strictly forbidden, unless permitted by WSO2 in accordance with the 
# WSO2 Commercial License available at https://wso2.com/licenses/eula/3.2
#
# --------------------------------------------------------------------------------------

apiVersion: v1
kind: Service
metadata:
  name: {{ template "resource.prefix" . }}-{{ .Release.Name }}
  namespace : {{ .Release.Namespace }}
  labels:
{{ include "micro-integrator.labels" . | indent 4 }}
spec:
  selector:
    deployment: {{ template "resource.prefix" . }}-{{ .Release.Name }}
  ports:
    - port: {{ add 8253 .Values.wso2.config.portOffset -10 }}
      protocol: TCP
      name: pass-through-https
    - port: {{ add 9201 .Values.wso2.config.portOffset -10 }}
      protocol: TCP
      name: metrics
    - port: {{ add 9164 .Values.wso2.config.portOffset -10 }}
      protocol: TCP
      name: management
    {{- if .Values.wso2.deployment.synapseTest.enabled }}
    - port: {{ add 9008 .Values.wso2.config.portOffset -10 }}
      protocol: TCP
      name: synapse-test
    {{- end}}
