{{- if .Values.wso2.deployment.mountCapps }}
# -------------------------------------------------------------------------------------
#
# Copyright (c) 2023, WSO2 LLC. (http://www.wso2.com). All Rights Reserved.
#
# This software is the property of WSO2 LLC. and its suppliers, if any.
# Dissemination of any information or reproduction of any material contained 
# herein is strictly forbidden, unless permitted by WSO2 in accordance with the 
# WSO2 Commercial License available at https://wso2.com/licenses/eula/3.2
#
# --------------------------------------------------------------------------------------

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Values.wso2.deployment.mountCapps.storage.storageClass }}
provisioner: {{ .Values.wso2.deployment.mountCapps.storage.provisioner }}
parameters:
{{ toYaml .Values.wso2.deployment.mountCapps.storage.parameters | indent 2 }}
{{- end}}
