{{ if and .Values.wso2.subscription.username .Values.wso2.subscription.password }}
# -------------------------------------------------------------------------------------
#
# Copyright (c) 2023, WSO2 LLC. (http://www.wso2.com). All Rights Reserved.
#
# This software is the property of WSO2 LLC. and its suppliers, if any.
# Dissemination of any information or reproduction of any material contained 
# herein is strictly forbidden, unless permitted by WSO2 in accordance with the 
# WSO2 Commercial License available at https://wso2.com/licenses/eula/3.2
#
# --------------------------------------------------------------------------------------

{{- $username := .Values.wso2.subscription.username }}
{{- $password := .Values.wso2.subscription.password }}
{{- $email := .Values.wso2.subscription.username }}
{{- $regId := .Values.containerRegistry }}
{{- $auth := printf "%s:%s" $username $password | b64enc }}
{{- $files := .Files }}
apiVersion: v1
kind: Secret
metadata:
  name: wso2micro-integrator-deployment-creds
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ $files.Get "auth.json" | replace "reg.id" $regId | replace "reg.username" $username | replace "reg.password" $password | replace "reg.email" $email | replace "reg.auth" $auth | b64enc }}
{{ end }}
