[server_config]
port = {{ .Values.wso2.config.serverPort }}

[heartbeat_config]
pool_size = {{ .Values.wso2.config.heartbeatPoolSize }}

[mi_user_store]
username = {{ .Values.wso2.config.miUserstore.username | quote }}
{{- if .Values.wso2.config.secureVault.enabled }}
password = "$secret{mi_admin_password}"
{{- else }}
password = {{ .Values.wso2.config.miUserstore.password | quote }}
{{- end }}

[keystore]
file_name = "conf/security/{{ .Values.wso2.config.keyStore.fileName }}"
{{- if .Values.wso2.config.secureVault.enabled }}
password = "$secret{keystore_password}"
key_password = "$secret{keystore_key_password}"
{{- else }}
password = "{{ .Values.wso2.config.keyStore.password }}"
key_password = "{{ .Values.wso2.config.keyStore.keyPassword }}"
{{- end }}

{{ if and (.Values.wso2.config.sso) (.Values.wso2.config.sso.enabled) }}
[truststore]
file_name = "conf/security/{{ .Values.wso2.config.trustStore.fileName }}"
{{- if .Values.wso2.config.secureVault.enabled }}
password = "$secret{truststore_password}"
{{- else }}
password = "{{ .Values.wso2.config.trustStore.password }}"
{{ end }}

[sso]
enable = true
client_id = {{ .Values.wso2.config.sso.clientId | quote }}
base_url = {{ .Values.wso2.config.sso.baseUrl | quote }}
jwt_issuer = {{ .Values.wso2.config.sso.jwtIssuer | quote }}
resource_server_URLs = {{ .Values.wso2.config.sso.resourceServerUrls}}
sign_in_redirect_URL = {{ .Values.wso2.config.sso.signInRedirectUrl | quote }}
{{- if .Values.wso2.config.sso.enablePKCE }}
enable_PKCE = {{ .Values.wso2.config.sso.enablePKCE }}
{{- end }}
{{- if .Values.wso2.config.sso.trustedAudience }}
additional_trusted_audience = {{ .Values.wso2.config.sso.trustedAudience }}
{{- end }}
{{- end }}

{{- if .Values.wso2.config.secureVault.enabled }}
[secrets]
mi_admin_password = {{ .Values.wso2.config.miUserstore.password | quote }}
keystore_password = {{ .Values.wso2.config.keyStore.password | quote }}
keystore_key_password = {{ .Values.wso2.config.keyStore.keyPassword | quote }}
truststore_password = {{ .Values.wso2.config.trustStore.password | quote }}
{{- end }}
