# AWS service configurations
aws:
  # -- AWS IAM serivce account name
  serviceAccountName: ""
  # AWS Elastic Container Registry (ECR) configurations
  ecr:
    # -- AWS Elastic Container Registry
    registry: ""
  # AWS Secret Manager configurations
  secretManager:
    # -- AWS Secret Manager secret provider class name
    secretProviderClass: ""
    secretIdentifiers:
      internalKeystorePassword:
        # -- Secret name for internal keystore password
        secretName: ""
        # -- Secret key for internal keystore password
        secretKey: ""
wso2:
  ingress:
    # -- Enable Ingress for MI
    enabled: true
    # -- Ingress class name
    ingressClassName: ""
    # -- (list) Ingress annotations
    annotations:
    # -- K8s TLS secret for configured hostname
    tlsSecret: ""

  config:
    # -- Port offset for Micro Integrator (https://apim.docs.wso2.com/en/latest/install-and-setup/setup/deployment-best-practices/changing-the-default-ports-with-offset/#changing-the-default-mi-ports)
    portOffset: 10
    admin:
      # -- Super admin username
      username: ""
      # -- Super admin password
      password: ""
      # -- Create super admin account
      createAdminAccount: false
    userstore:
      file:
        # -- Enable/Disable file based userstore
        enabled: true
        # rdbms:
        #   # -- User Database URL
        #   url: ""
        #   # -- User Database username
        #   username: ""
        #   # -- User Database password
        #   password: ""
        #   jdbc:
        #     # -- JDBC driver class name of the User Database
        #     driver: ""
        #     # -- (list) JDBC connection pool parameters of the User Database
        #     poolParameters:
    secureVault:
      # -- Enable/Disable secure vault
      enabled: false
    # # -- Enable/Disable coordination
    # coordination:
    #   # -- Node ID for coordination
    #   nodeId: ""
    #   rdbms:
    #     # -- Coordination Database URL
    #     url: ""
    #     # -- Coordination Database username
    #     username: ""
    #     # -- Coordination Database password
    #     password: ""
    #     jdbc:
    #       # -- JDBC driver class name of the Coordination Database
    #       driver: ""
    #       # -- (list) JDBC connection pool parameters of the Coordination Database
    #       poolParameters:
    keyStore:
      primary:
        # -- Primary keystore file name
        fileName: "wso2carbon.jks"
        # -- Primary keystore alias
        alias: "wso2carbon"
        # -- Primary keystore password
        password: ""
        # -- Primary keystore key password
        keyPassword: ""
      internal:
        # -- Internal keystore file name
        fileName: "wso2carbon.jks"
        # -- Internal keystore alias
        alias: "wso2carbon"
        # -- Internal keystore password
        password: ""
        # -- Internal keystore key password
        keyPassword: ""
    trustStore:
      primary:
        # -- Primary truststore file name
        fileName: "client-truststore.jks"
        # -- Primary truststore password
        password: ""
    dashboard:
      # -- MI Dashboard URL
      url: ""
      # -- The time interval (in seconds) between two heartbeats sent from the Micro Integrator to the dashboard server
      heartbeatInterval: 5
  deployment:
    securityContext:
      # -- The UID to run the entrypoint of the container process
      runAsUser: ""
    # -- Hostname of the Micro Integrator deployment
    hostname: ""
    # -- Build version of the Micro Integrator
    BuildVersion: "4.2.0"
    # -- K8s secret name which contains JKS files
    JKSSecretName: ""
    image:
      # -- Container image repository name
      repository: ""
      # -- Container image digest
      digest: ""
      # -- Container image pull policy. Refer (https://kubernetes.io/docs/concepts/containers/images/#updating-images)
      pullPolicy: Always

    # -- Kubernetes Probes (https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/)
    probes:
      # -- Startup probe executed prior to Liveness Probe taking over
      startup:
        # -- Number of seconds after the container has started before startup probes are initiated
        initialDelaySeconds: 5
        # -- How often (in seconds) to perform the probe
        periodSeconds: 3
        # -- Number of attempts
        failureThreshold: 40
      # -- Indicates whether the container is running
      liveness:
        # -- How often (in seconds) to perform the probe
        periodSeconds: 10
        # -- Indicates whether the container is ready to service requests
      readiness:
        # -- Number of seconds after the container has started before readiness probes are initiated
        initialDelaySeconds: 60
        # -- How often (in seconds) to perform the probe
        periodSeconds: 1

    # -- Number of deployment replicas
    replicas: 1
    # HPA configurations
    # -- Min replica count for HPA (https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/)
    minReplicas: 1
    # -- Max replica count for HPA (https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/)
    maxReplicas: 2
    # -- Average CPU utilization percentage for HPA
    cpuUtilizationPercentage: 75
    # -- Average memory utilization percentage for HPA
    memoryUtilizationPercentage: 75
    # -- Pod disruption budget configurations (https://kubernetes.io/docs/tasks/run-application/configure-pdb/)
    minAvailable: 1

    strategy:
      rollingUpdate:
        # -- The maximum number of pods that can be scheduled above the desired number of pods.
        maxSurge: 1
        # -- The maximum number of pods that can be unavailable during the update.
        maxUnavailable: 0

    # These are the minimum resource recommendations for running WSO2 Micro Integrator
    resources:
      requests:
        # -- The minimum amount of memory that should be allocated for a Pod
        memory: "512Mi"
        # -- The minimum amount of CPU that should be allocated for a Pod
        cpu: "500m"
      limits:
        # -- The maximum amount of memory that should be allocated for a Pod
        memory: "1Gi"
        # -- The maximum amount of CPU that should be allocated for a Pod
        cpu: "1000m"

      # JVM settings
      # These are the resource allocation configurations associated with the JVM
      jvm:
        memory:
          # -- The minimum amount of memory that should be allocated for the JVM
          xms: "512m"
          # -- The maximum amount of memory that should be allocated for the JVM
          xmx: "1024m"

    # -- (list) Environment variables for the Micro integrator deployment
    envs:
    # wso2_oh_sample_baseUrl: "http://localhost:8290/services/odata"

    # Configure synapse testing
    synapseTest:
      # -- Enable/Disable synapse testing
      enabled: false
    # Persistent volume configurations
    storage:
      # -- Persistent volume storage class name
      storageClass: ""
      # -- Persistent volume storage capacity
      capacity: ""
      # -- EFS volume handle
      volumeHandle: ""
